export const ProcessingStage = {
  IDLE: 'IDLE',
  ANALYZING: 'ANALYZING',
  GENERATING_SYLLABLES: 'GENERATING_SYLLABLES',
  MATCHING_VOCAL_PATTERN: 'MATCHING_VOCAL_PATTERN',
  APPLYING_SPECTRAL_EQ: 'APPLYING_SPECTRAL_EQ',
  DE_ESSING: 'DE_ESSING',
  RENDERING: 'RENDERING',
  COMPLETE: 'COMPLETE',
  ERROR: 'ERROR'
};